# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_comments', '0003_add_submit_date_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='comment',
            name='reply_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='root_id',
            field=models.IntegerField(default=0),
        ),
    ]
